### ISSUE TITLE
Unable to install gauss-psf-cuda package

### ISSUE THREAD

**Issue by charleshuang880730** [cake-lab/HybridDepth#1]
Hi,

Thank you for your hard work on this project. I have encountered an issue while using the command ```conda env create -f environment.yml```. It seems that the ```gauss-psf-cuda``` package cannot be found through pip install.

Could you please provide an alternative method to install this package or advise on how to resolve this issue?

Thank you for your assistance.

**Comment by charleshuang880730** [comment]
Additionally, I have two more questions:

1. Could you provide detailed implementation steps for capturing photos with varying focus_dist using an Android phone? Do I need to specify a particular focus region?

2. Should I use the focus distance provided by the Android phone as an input to the model, considering that the focus distance values obtained may vary between different phone models?

**Comment by AshkanGanj** [comment]
Hello,

Thank you for pointing out this problem. The `gauss-psf-cuda` package is a custom Python package and needs to be installed manually. We have updated the environment.yaml file and also added the instructions for installing the `gauss-psf-cuda` package manually.

Please run this command to install the package:
`python utils/synthetic/gauss_psf/setup.py install`
This should fix your problem.


Answers to your questions: 
**Re1**: We are going to open source a capturing application, but you can use any mobile application such as Open Camera for capturing a focal stack with different focus distances. As long as you can manually change the focus planes, it will work fine.

**Re2:** Using the provided focus distances by your mobile phone is possible if you are sure that the values are correct. For some devices, the focus distances may not provide correct metric information in the real world, but for most newer devices, this is not the case, and you can use reported values after changing them to metric units. In the Open Camera app, you can see the focus distance in meters, and you can use those values as input to the model, so I recommend to use that.


I am closing this issue right now since the provided instructions should fix the problem, but feel free to reopen it if you have any questions.

**Comment by charleshuang880730** [comment]
> Hello,
> 
> Thank you for pointing out this problem. The `gauss-psf-cuda` package is a custom Python package and needs to be installed manually. We have updated the environment.yaml file and also added the instructions for installing the `gauss-psf-cuda` package manually.
> 
> Please run this command to install the package: `python utils/synthetic/gauss_psf/setup.py install` This should fix your problem.
> 
> Answers to your questions: **Re1**: We are going to open source a capturing application, but you can use any mobile application such as Open Camera for capturing a focal stack with different focus distances. As long as you can manually change the focus planes, it will work fine.
> 
> **Re2:** Using the provided focus distances by your mobile phone is possible if you are sure that the values are correct. For some devices, the focus distances may not provide correct metric information in the real world, but for most newer devices, this is not the case, and you can use reported values after changing them to metric units. In the Open Camera app, you can see the focus distance in meters, and you can use those values as input to the model, so I recommend to use that.
> 
> I am closing this issue right now since the provided instructions should fix the problem, but feel free to reopen it if you have any questions.

@AshkanGanj Hi, 

Thank you for your previous response. 

I have an additional question regarding the practical application of capturing images with different focus distances using the Open Camera app. When capturing a focal stack with five images at different focus distances, does the range of focus distances significantly affect the model's results? Are there any specific limitations or recommended ranges for the focus distances that should be considered to ensure optimal model performance in real-world scenarios?
